services:
  - type: web
    name: cafe-website
    env: node
    buildCommand: |
      npm install
      npm install -g vite
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 